# Generated by Django 5.0.1 on 2024-01-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_customuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.IntegerField(choices=[(0, 'Patient'), (1, 'Doctor')], default=0),
        ),
    ]
