# Generated by Django 5.0.1 on 2024-01-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
